# -*- coding: utf-8 -*-
# Generated by https://github.com/verloop/twirpy/protoc-gen-twirpy.  DO NOT EDIT!
# source: haberdasher.proto

from google.protobuf import symbol_database as _symbol_database

from twirp.base import Endpoint
from twirp.server import TwirpServer
from twirp.client import TwirpClient

_sym_db = _symbol_database.Default()

class HaberdasherServer(TwirpServer):

	def __init__(self, *args, service, server_path_prefix="/twirp"):
		super().__init__(service=service)
		self._prefix = F"{server_path_prefix}/twitch.twirp.example.Haberdasher"
		self._endpoints = {
			"MakeHatTest": Endpoint(
				service_name="Haberdasher",
				name="MakeHatTest",
				function=getattr(service, "MakeHatTest"),
				input=_sym_db.GetSymbol("twitch.twirp.example.Size"),
				output=_sym_db.GetSymbol("twitch.twirp.example.Hat"),
			),
			"GetDollarRate": Endpoint(
				service_name="Haberdasher",
				name="GetDollarRate",
				function=getattr(service, "GetDollarRate"),
				input=_sym_db.GetSymbol("twitch.twirp.example.Empty"),
				output=_sym_db.GetSymbol("twitch.twirp.example.DollarRate"),
			),
		}

class HaberdasherClient(TwirpClient):

	def MakeHatTest(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
		return self._make_request(
			url=F"{server_path_prefix}/twitch.twirp.example.Haberdasher/MakeHatTest",
			ctx=ctx,
			request=request,
			response_obj=_sym_db.GetSymbol("twitch.twirp.example.Hat"),
			**kwargs,
		)

	def GetDollarRate(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
		return self._make_request(
			url=F"{server_path_prefix}/twitch.twirp.example.Haberdasher/GetDollarRate",
			ctx=ctx,
			request=request,
			response_obj=_sym_db.GetSymbol("twitch.twirp.example.DollarRate"),
			**kwargs,
		)
